profile = "default"

[msbuild]
project = ["./FactorioSharp.Instrumentation/FactorioSharp.Instrumentation.csproj", "./FactorioSharp.Instrumentation.OpenTelemetry/FactorioSharp.Instrumentation.OpenTelemetry.csproj"]

[github]
user = "FactorioSharp"
repo = "FactorioSharp.Instrumentation"
version_prefix = "v"
