name: .NET - Build and Publish 

on:
  push:
    tags: 
    - v*

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:    
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        filter: tree:0

    - name: Install .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install dotnet-releaser
      shell: bash
      run: dotnet tool install --global dotnet-releaser

    - name: Library - Build, Pack and Publish
      shell: bash
      run: dotnet-releaser run --nuget-token "${{secrets.NUGET_TOKEN}}" --github-token "${{secrets.GITHUB_TOKEN}}" --github-token-extra "${{secrets.API_GITHUB_TOKEN}}" dotnet-releaser.libraries.toml

    - name: Application - Build, Pack and Publish
      shell: bash
      run: dotnet-releaser run --nuget-token "${{secrets.NUGET_TOKEN}}" --github-token "${{secrets.GITHUB_TOKEN}}" --github-token-extra "${{secrets.API_GITHUB_TOKEN}}" dotnet-releaser.libraries.toml
      
permissions:
  contents: write
